spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USERNAME}
    url: jdbc:mysql://localhost:3306/backoffice
    password: ${MYSQL_PASSWORD}
  jackson:
    time-zone: Asia/Seoul
  jpa:
    properties:
      hibernate:
        format_sql: 'true'
        use_sql_comments: 'true'
        show_sql: 'true'
        default_batch_fetch_size: 20
    hibernate:
      ddl-auto: create-drop
  data:
    redis:
      repositories:
        enabled: false
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
      max-request-size: 2MB

# jwt token secret key
jwt:
  secret: ${JWT_SECRET}

# logging level : security error
logging:
  level:
    org.springframework.security: ERROR

cloud:
  aws:
    s3:
      bucket: ${YOUR_BUCKET_NAME}
    stack:
      auto: false
    region:
      static: ${YOUR_REGION}
    credentials:
      accessKey: ${YOUR_ACCESS_KEY}
      secretKey: ${YOUR_SECRET_KEY}